CREATE TABLE IF NOT EXISTS credentials_match(id BIGINT NOT NULL AUTO_INCREMENT, uuid VARCHAR(32), uname TEXT, os INT NOT NULL, PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS operating_systems(id INT NOT NULL AUTO_INCREMENT, os TEXT, PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS blacklist(id BIGINT NOT NULL AUTO_INCREMENT, os INT, process TEXT, PRIMARY KEY(id));